### ISSUE TITLE
Get a graphical UI

### ISSUE THREAD

**Issue by xackery** [xackery/eqemupatcher#3]

**Comment by xackery** [comment]
Is this worth it? I think it's better to remove the patcher from anyone's perspective.

**Comment by Mortow** [comment]
Maybe make it an option to show it or not.  I personally would like to see the patcher and be able to modify the background and such or at the very least be permitted to opt in or out of seeing it.  As a server owner, I like to see what is going on and be able to monitor it

**Comment by xackery** [comment]
This was resolved
